In [7]:
import yfinance as yf
import pandas as pd

data = yf.Ticker("^GSPC")
data.info.keys()

dict_keys(['maxAge', 'priceHint', 'previousClose', 'open', 'dayLow', 'dayHigh', 'regularMarketPreviousClose', 'regularMarketOpen', 'regularMarketDayLow', 'regularMarketDayHigh', 'volume', 'regularMarketVolume', 'averageVolume', 'averageVolume10days', 'averageDailyVolume10Day', 'bid', 'ask', 'bidSize', 'askSize', 'fiftyTwoWeekLow', 'fiftyTwoWeekHigh', 'allTimeHigh', 'allTimeLow', 'fiftyDayAverage', 'twoHundredDayAverage', 'currency', 'tradeable', '52WeekChange', 'quoteType', 'symbol', 'language', 'region', 'typeDisp', 'quoteSourceName', 'triggerable', 'customPriceAlertConfidence', 'hasPrePostMarketData', 'firstTradeDateMilliseconds', 'regularMarketChange', 'regularMarketDayRange', 'fullExchangeName', 'averageDailyVolume3Month', 'fiftyTwoWeekLowChange', 'fiftyTwoWeekLowChangePercent', 'fiftyTwoWeekRange', 'fiftyTwoWeekHighChange', 'fiftyTwoWeekHighChangePercent', 'fiftyTwoWeekChangePercent', 'fiftyDayAverageChange', 'fiftyDayAverageChangePercent', 'twoHundredDayAverageChange', 'twoHundredDayAverageChangePercent', 'sourceInterval', 'exchangeDataDelayedBy', 'marketState', 'cryptoTradeable', 'regularMarketChangePercent', 'regularMarketPrice', 'shortName', 'longName', 'corporateActions', 'regularMarketTime', 'exchange', 'messageBoardId', 'exchangeTimezoneName', 'exchangeTimezoneShortName', 'gmtOffSetMilliseconds', 'market', 'esgPopulated', 'trailingPegRatio'])

In [8]:
# Get historical data
hist = data.history(period="max")

# Calculate monthly gross close price increase
SP500_data = hist.groupby(pd.Grouper(freq='ME')).agg({
    'Close': ['first', 'last']
}).droplevel(0, axis=1)
SP500_data.columns = ['First_Closing_Price', 'Final_Closing_Price']
SP500_data['Monthly_Increase'] = SP500_data['Final_Closing_Price'] - SP500_data['First_Closing_Price']

SP500_data

,First_Closing_Price,Final_Closing_Price,Monthly_Increase
Date,,,
1927-12-31 00:00:00-05:00,17.660000,17.660000,0.000000
1928-01-31 00:00:00-05:00,17.760000,17.570000,-0.190001
1928-02-29 00:00:00-05:00,17.530001,17.260000,-0.270000
1928-03-31 00:00:00-05:00,17.299999,19.280001,1.980001
1928-04-30 00:00:00-04:00,18.910000,19.750000,0.840000
...,...,...,...
2025-11-30 00:00:00-05:00,6851.970215,6849.089844,-2.880371
2025-12-31 00:00:00-05:00,6812.629883,6845.500000,32.870117
2026-01-31 00:00:00-05:00,6858.470215,6939.029785,80.559570
2026-02-28 00:00:00-05:00,6976.439941,6878.879883,-97.560059
2026-03-31 00:00:00-04:00,6881.620117,6795.990234,-85.629883

In [9]:
# Split date into month and year
SP500_data= SP500_data.reset_index()
SP500_data.columns = ['Date', 'First_Closing_Price', 'Final_Closing_Price', 'Monthly_Increase']
SP500_data['Month'] = SP500_data['Date'].dt.month
SP500_data['Year'] = SP500_data['Date'].dt.year

SP500_data

,Date,First_Closing_Price,Final_Closing_Price,Monthly_Increase,Month,Year
0,1927-12-31 00:00:00-05:00,17.660000,17.660000,0.000000,12,1927
1,1928-01-31 00:00:00-05:00,17.760000,17.570000,-0.190001,1,1928
2,1928-02-29 00:00:00-05:00,17.530001,17.260000,-0.270000,2,1928
3,1928-03-31 00:00:00-05:00,17.299999,19.280001,1.980001,3,1928
4,1928-04-30 00:00:00-04:00,18.910000,19.750000,0.840000,4,1928
...,...,...,...,...,...,...
1175,2025-11-30 00:00:00-05:00,6851.970215,6849.089844,-2.880371,11,2025
1176,2025-12-31 00:00:00-05:00,6812.629883,6845.500000,32.870117,12,2025
1177,2026-01-31 00:00:00-05:00,6858.470215,6939.029785,80.559570,1,2026
1178,2026-02-28 00:00:00-05:00,6976.439941,6878.879883,-97.560059,2,2026
1179,2026-03-31 00:00:00-04:00,6881.620117,6795.990234,-85.629883,3,2026

In [10]:
def getSP500_data():
    return SP500_data